[package]
name = "rpfm_ui"
version = "2.1.4"
build = "build.rs"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
description = "A modding tool for Total War games."
edition = "2018"

[dependencies]
# Internal dependencies.
rpfm_error = { path = "../rpfm_error" }
rpfm_lib = { path = "../rpfm_lib" }

# Config dependencies.
lazy_static = "^1.2"

# Serialization dependencies.
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
ron = "^0.5"
bincode = "^1.1"

# Date conversion support.
chrono = "^0.4"

# Support for checking/downloading schemas.
restson = "^0.6"
reqwest = { version = "^0.10", features = ["blocking", "json"] }

# Support for Regex operations.
regex = "^1"

# Support for open files in a native way.
open = "^1.2"

# Qt dependencies.
cpp_core = "^0.5"
qt_core = "^0.4"
qt_gui = "^0.4"
qt_widgets = "^0.4"

# Support for formatting math operations.
meval = "^0.2"

# UUID Generation support.
uuid = { version = "^0.8", features = ["v4"] }

# Translation support.
fluent = "^0.12"
fluent-bundle = "^0.12"
unic-langid = { version = "^0.9", features = ["unic-langid-macros"] }

# Improved multi-thread Support.
crossbeam = "^0.7"
rayon = "^1.3"

# Logging support.
log = "^0.4"
simplelog = "^0.7.0"

# Windows resources support.
[target.'cfg(windows)'.build-dependencies]
winres = "^0.1"
