# Workspace containing all RPFM crates.
[workspace]
members = [
	"rpfm_error",
    "rpfm_lib",
    "rpfm_cli",
    "rpfm_ui",
]

[profile.dev]
incremental = true

[profile.release]
lto = true
debug = true
