[package]
name = "rpfm_test_updater"
version = "0.1.0"
authors = ["Ismael Gutiérrez González <frodo_gv@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
