[package]
name = "rpfm_lib"
version = "2.1.4"
build = "build.rs"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
description = "RPFM Lib, where all the magic happens."
edition = "2018"

[lib]
# Disable doctest, as we have none of them but still `cargo test` tries to execute `RON` code as doctests, and fails.
doctest = false

[dependencies]
# Internal dependencies.
rpfm_error = { path = "../rpfm_error" }

# Configuration support.
directories = "^2.0"
lazy_static = "^1.2"
indexmap = "^1.5"

# Decoding/Encoding support.
itertools = "^0.9"
byteorder = "^1.3"
encoding = "^0.2"
bitflags = "^1.0"
regex = "^1"

# UUID Generation support.
uuid = { version = "^0.8", features = ["v4"] }

# Date manipulation support.
chrono = "^0.4"

# Update support.
reqwest = { version = "^0.10", features = ["blocking", "json"] }

# Serialization support.
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serde-xml-rs = "^0.4"
bincode = "^1.1"
csv = "^1.1"
ron = "^0.5"

# Git support.
git2 = "^0.13"

# Compression support.
xz2 = "^0.1"

# Multithread iterator support.
rayon = "^1.3"

# F16 Support.
half = "^1.4"

# Fractions support
fraction = "^0.6"
