name: Rust
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: self-hosted 
    strategy:
      matrix:
        os: [windows-latest]
        version: ['5.9']
    steps:
      - name: Compilation on Windows
        if: startsWith(matrix.os, 'windows')

        run: |
          C:\CraftRoot\craft\craftenv.ps1
          cargo build --verbose --release
        shell: pwsh   
