name: Rust
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        version: ['5.9']
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Compilation on Windows
        if: startsWith(matrix.os, 'windows')

        run: |
          $scriptPath = ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/Frodo45127/craft/master/setup/install_craft.ps1'))
          Invoke-Command -ScriptBlock ([scriptblock]::Create($scriptPath)) -ArgumentList "C:\hostedtoolcache\windows\Craft"
        shell: pwsh   
        
      - name: Compilsation on Windows
        if: startsWith(matrix.os, 'windows')

        run: |
          C:\hostedtoolcache\windows\Craft\craft\craftenv.ps1
          craft -i ktexteditor
          cargo build --verbose --release
        shell: pwsh   
