name: Rust
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions/cache@v2
        with:
          path: |
            C:\hostedtoolcache\windows\Craft
          key: ${{ runner.os }}-cargo-${{ hashFiles('C:\hostedtoolcache\windows\Craft\craft\craftenv.ps1') }}

      - name: Installing Qt5 & KTextEditor on Windows
        if: startsWith(matrix.os, 'windows') && steps.cache.outputs.cache-hit != 'true'
      
        run: |
          $scriptPath = ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/Frodo45127/craft/master/setup/install_craft.ps1'))
          Invoke-Command -ScriptBlock ([scriptblock]::Create($scriptPath)) -ArgumentList "C:\hostedtoolcache\windows\Craft"
          C:\hostedtoolcache\windows\Craft\craft\craftenv.ps1
          craft -i --ci-mode ktexteditor
        shell: pwsh   
      
      - name: Build on Windows
        if: startsWith(matrix.os, 'windows')
      
        run: |
          C:\hostedtoolcache\windows\Craft\craft\craftenv.ps1
          cd D:/a/rpfm_test_updater/rpfm_test_updater
          cargo build --release
        shell: pwsh   
